# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infomarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='bet',
            new_name='choice',
        ),
    ]
