# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomarket', '0002_auto_20161207_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='total_bet',
            field=models.IntegerField(default=0),
        ),
    ]
